### PR TITLE
Spirit Day updates

### PR DESCRIPTION
**Pull request by leonoverweel**
For our purple friday theme, this PR changes:
- The `$pink` color from `#ff29a9` to `#b45ad0`
- The logo to one with a matching color. 

We should merge and deploy this change around Thursday evening (2019-12-12), and then revert it back on Saturday (2019-12-14).

TODO: @FaaPz we also need to add a binding for the purple friday page; [see this card](https://github.com/orgs/ASVGay/projects/1#card-29835003). I don't know how to do this myself.

### CODE REVIEW

**Comment by leonoverweel** [comment]
Since this is on my fork, it probably makes most sense to get this merged to master and deployed, and then you can add the page on a different branch. Sound good @FaaPz?

**Comment by Slartibartfass42** [comment]
Wouldn't it make sense to automate this?

**Comment by leonoverweel** [comment]
It would but I have no idea how to deploy in the first place. Once we get a nice CI flow set up I think we can start looking into things like this.

**Comment by leonoverweel** [comment]
Done pre-github.

**Pull request closed without merging**
